### ISSUE TITLE
Incident: API down

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/daimo#1160]
## Summary

2h API downtime, triggered by null value in shovel DB

## Timeline

2024-06-15, Pacific time

- **11:59am** - [a request was created](https://logs.betterstack.com/team/183561/tail?s=796519%2C796523%2C870372&q=request_created+15844324#1718477997493990-64000980). resulting `request_created` row appears with with metadata=null. 
- **~12pm** - Prod API down, status: watcher-not-ticking.
- **13:40pm** - hotfix ready https://github.com/daimo-eth/daimo/pull/1161
- **13:57pm** - Prod API back up

#### Watcher ticks failing

https://api.daimo.xyz/chain/8453/health

#### Shovel

**Logs look OK.** Latest block looks correct in Shovel DB:

<img width="429" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/ee95ecd7-0abf-4281-b2ac-804384a0bf03">

^ matches Basescan

<img width="1616" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/5912cad2-ccb5-43f0-a92a-50c3c2505307">

https://logs.betterstack.com/team/183561/tail?s=796523

**Error in requestIndexer:**

```
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr [SHOVEL] tick error TypeError: Cannot read properties of null (reading 'length')
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at bytesToHex (/usr/src/app/node_modules/viem/utils/encoding/toHex.ts:133:29)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at rowToRequestCreatedLog (/usr/src/app/packages/daimo-api/src/contract/requestIndexer.ts:372:15)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at Array.map (<anonymous>)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at RequestIndexer.loadCreated (/usr/src/app/packages/daimo-api/src/contract/requestIndexer.ts:127:30)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at RequestIndexer.load (/usr/src/app/packages/daimo-api/src/contract/requestIndexer.ts:70:23)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at async Promise.all (index 1)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at Watcher.index (/usr/src/app/packages/daimo-api/src/shovel/watcher.ts:163:7)
2024-06-15 13:37:23.150 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr     at Timeout._onTimeout (/usr/src/app/packages/daimo-api/src/shovel/watcher.ts:121:29)
2024-06-15 13:37:23.540 [daimo_api] DaimoApiCluster-production api-task-production:21 stderr [SWAPCOIN] SKIPPING 15844324-15847246, already processed thru 15844324
```

**Comment by nalinbhardwaj** [comment]
### Culprit Shovel row

![image (2)](https://github.com/daimo-eth/daimo/assets/6984346/a2eeade4-6a6b-4785-9f38-f350194637aa)

Unclear why this is null, current best guesses:

1. [Fetched from Alchemy, maybe alchemy returned bad data?](https://logs.betterstack.com/team/183561/tail?s=796519%2C796523%2C870372&q=request_created%2015844324#1718477997493990-64000980)
2. [Some panics around the fetching, could be related](https://logs.betterstack.com/team/183561/tail?s=796519%2C796523%2C870372&q=ecs_task_definition%3D%22shovel-task-production%3A8%22#1718484[…]25000045)

**Comment by dcposch** [comment]
## Fixes

- [x] #1161  , handle NULLs in shovel logs
- [ ] Shovel bug (TODO)
- [ ] Migrate shovel DB, make columns non-nullable
- [ ] Add PagerDuty

As a follow up, we could also add typing to our SQL via eg. Prisma or TypeSQL. In this case, this would've replaced the `any` in `function rowToRequestCreatedLog(r: any)`, and we would've caught that required columns like `metadata` were actually nullable.

**Comment by nalinbhardwaj** [comment]
Cause request transaction: https://basescan.org/tx/0xe08e8dc1f62566f8f0e0ce0289ba5fd41cfc555ec61afe73eccf54db6540be0c
