### ISSUE TITLE
Too many transfer logs on mainnet

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#366]
```
/opt/render/project/src/packages/daimo-api/src/cron.ts:55
Oct 28 06:32:41 PM      this.transfersQueue.push(...logs);
Oct 28 06:32:41 PM                          ^
Oct 28 06:32:41 PM  RangeError: Maximum call stack size exceeded
Oct 28 06:32:41 PM      at pipeTransfers (/opt/render/project/src/packages/daimo-api/src/cron.ts:55:25)
Oct 28 06:32:41 PM      at CoinIndexer.pipeAllTransfers (/opt/render/project/src/packages/daimo-api/src/contract/coinIndexer.ts:61:5)
```

And another call of `JSON.stringify` failing at https://github.com/daimo-eth/daimo/blob/6e09c5fc9426576612c449cff951136ad9ef0122/packages/daimo-api/src/pushNotifier.ts#L82

**Comment by dcposch** [comment]
fixed
